<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Deadlines derived from confirmed documents (SPEC.md §6/§7). Generated by the
 * rules engine (M4) and recomputed daily (M7). tenant_id is denormalised from
 * the parent document so the cockpit can query deadlines directly under tenant
 * scope.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('deadlines', function (Blueprint $table) {
            $table->id();
            $table->foreignId('tenant_id')->constrained()->cascadeOnDelete();
            $table->foreignId('document_id')->constrained()->cascadeOnDelete();
            $table->date('due_date');
            $table->unsignedSmallInteger('lead_days')->default(30);
            $table->string('status')->default('safe'); // App\Enums\DeadlineStatus
            $table->foreignId('responsible_user_id')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();

            $table->index(['tenant_id', 'status']);
            $table->index(['tenant_id', 'due_date']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('deadlines');
    }
};
