<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Compliance\DeadlineGenerator;
use App\Enums\PersonRole;
use App\Enums\UserRole;
use App\Models\Document;
use App\Models\Entity;
use App\Models\Person;
use App\Models\RulePack;
use App\Models\Tenant;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed demo accounts for local/manual testing. All use password "password".
     */
    public function run(): void
    {
        // The UAE rule pack (the moat) — document types + deadline logic.
        $this->call(UaeRulePackSeeder::class);

        // Cross-tenant platform operator (no tenant).
        User::factory()->platformAdmin()->create([
            'name' => 'Platform Admin',
            'email' => 'admin@example.com',
        ]);

        // A demo agency tenant, its owner, and a couple of client entities.
        $agency = Tenant::factory()->agency()->create(['name' => 'Demo PRO Agency']);
        User::factory()->for($agency)->create([
            'name' => 'Agency Owner',
            'email' => 'agency@example.com',
            'role' => UserRole::AgencyOwner,
        ]);
        Entity::factory()->for($agency)->count(2)->create()->each(function (Entity $entity): void {
            Person::factory()->forEntity($entity)->create(['role' => PersonRole::Owner]);
            Person::factory()->forEntity($entity)->count(2)->create(['role' => PersonRole::Employee]);
        });

        // A demo SME tenant, its owner, and its own business entity.
        $sme = Tenant::factory()->sme()->create(['name' => 'Demo SME']);
        User::factory()->for($sme)->create([
            'name' => 'SME Owner',
            'email' => 'sme@example.com',
            'role' => UserRole::SmeOwner,
        ]);
        $smeEntity = Entity::factory()->for($sme)->create(['legal_name' => 'Demo SME Trading LLC']);
        $smeOwner = Person::factory()->forEntity($smeEntity)->create(['role' => PersonRole::Owner]);

        // Demo confirmed documents, with deadlines + alerts generated by the engine.
        $pack = RulePack::activeFor('AE');
        $generator = app(DeadlineGenerator::class);

        $tradeLicence = Document::factory()->forEntity($smeEntity)->confirmed()->create([
            'document_type_id' => $pack->documentType('trade_licence')->id,
            'issue_date' => now()->subYear()->subMonths(2)->toDateString(),
            'expiry_date' => now()->addMonths(2)->toDateString(),
        ]);
        $generator->generate($tradeLicence);

        $visa = Document::factory()->forPerson($smeOwner)->confirmed()->create([
            'document_type_id' => $pack->documentType('residence_visa')->id,
            'issue_date' => now()->subYears(2)->addMonth()->toDateString(),
            'expiry_date' => now()->addMonth()->toDateString(),
        ]);
        $generator->generate($visa);
    }
}
